config = {
    "data": {
        "val_frac": 0.01,
        "dir": "data",
        "files": [
            "bleak_house.txt",
            "christmas_carol.txt",
            "david_copperfield.txt",
            "expectations.txt",
            "hard_times.txt",
            "little_dorrit.txt",
            "mutual_friend.txt",
            "oliver_twist.txt",
            "pickwick_papers.txt",
            "tale_of_two_cities.txt",
            "dombey_son.txt",
            "mystery_of_edwin_drood.txt",
            "martin_chuzzlewit.txt",
            "uncommercial_traveller.txt",
            "life_of_charles_dickens.txt",
            "child_dream.txt",
            "mugby_junction.txt",
            "hunted_down.txt",
            "pictures_from_italy.txt",
            "magic_fishbone.txt",
            "christmas_stories.txt",
            "critical_study.txt",
        ],
    },
    "model": {
        "emb_dim": 512,
        "num_heads": 16,
        "num_blocks": 6,
        "dropout": 0.1,
    },
    "lr": 1e-4,
    "batch_size": 128,
    "max_context": 64,
    "max_iters": 10000,
    "eval_iters": 100,
    "eval_interval": 1000,
    "generate": {
        "prompt": "It was a dark and stormy night",
        "n_tokens": 200,
        "temperature": 1.2,
        "top_k": 5,
    },
}
